# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: the programmer in me...

# Content
excerpt_link: Read More

# Header  nav
menu:
  Home: /
  Projects: /projects
  About: /about

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  Images: icon-image
  Wiki: icon-wiki
  Favorites: icon-Favorites
  Contact: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics: UA-42793939-1
favicon: /favicon.png
twitter: sam_twite
google_plus:
fb_admins:
fb_app_id:
